{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ template "origin-ca-issuer.serviceAccountName" . }}
  namespace: {{ include "origin-ca-issuer.namespace" . }}
  {{- if .Values.controller.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.controller.serviceAccount.annotations }}
  {{- end }}
  labels:
    app: {{ include "origin-ca-issuer.name" . }}
    app.kubernetes.io/name: {{ include "origin-ca-issuer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "controller"
    helm.sh/chart: {{ include "origin-ca-issuer.chart" . }}
{{- end }}
