apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
- rbac/role-binding.yaml
- rbac/role.yaml
- manifests/deployment.yaml
- manifests/namespace.yaml
- manifests/serviceaccount.yaml
