---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: originissuer-control
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.k8s.cloudflare.com
  resources:
  - originissuers
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.k8s.cloudflare.com
  resources:
  - originissuers/status
  verbs:
  - get
  - patch
  - update
