apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: originissuer-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: originissuer-control
subjects:
  - kind: ServiceAccount
    name: originissuer-control
    namespace: origin-ca-issuer
