---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: originissuer-control
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests/status
  verbs:
  - patch
- apiGroups:
  - cert-manager.k8s.cloudflare.com
  resources:
  - clusteroriginissuers
  - originissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.k8s.cloudflare.com
  resources:
  - clusteroriginissuers/status
  - originissuers/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/status
  verbs:
  - patch
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - clusteroriginissuers.cert-manager.k8s.cloudflare.com/*
  - originissuers.cert-manager.k8s.cloudflare.com/*
  resources:
  - signers
  verbs:
  - sign
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
