
---
# permissions to approve all cert-manager.k8s.cloudflare.com requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:cert-manager-k8s-cloudflare-com
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - originissuers.cert-manager.k8s.cloudflare.com/*
